### PR TITLE
Delete practice page as it's confusing for users #206

### PR DESCRIPTION
**Pull request by springdo**
**What does this do?**
Removes the `practices` description page from the CMS as it's confusing

### CODE REVIEW

**Comment by springdo** [comment]
Who ever views this issue to validate it might find the practice is still there in the CMS - this is because the CMS is reading all the practices in the preview from `master` branch

**Comment by springdo** [comment]
closes #206

**Comment by rdebeasi** [comment]
Side effect: practices item on sidebar menu is gone. I think that's ok - it was confusing in usability testing.

**Comment by rdebeasi** [comment]
Confirmed that admin looks good now that the change is merged.

**Pull request merged**
