### PR TITLE
fix(branding): practice colors match loop

### PR DESCRIPTION
**Pull request by lallmon**
https://github.com/openpracticelibrary/opl-fe/issues/178

Matching branding to the loop colors

### CODE REVIEW

**Comment by shaheinm** [comment]
Is this how we want it to look? 
Screen Shot 2020-08-03 at 4 14 13 PM

I like the idea, but I think the margins and spacing for the button and text content made things a bit more readable. Just my thoughts, though. If we're going this way, I'll back it regardless.

**Comment by shaheinm** [comment]
I also think some of the practices with embedded images near the top clash a bit. Like AEIOU Observation Framework:
Screen Shot 2020-08-03 at 4 17 47 PM

**Comment by lallmon** [comment]
Do you mean inside or outside the button? This is really just a pass for branding changes and simplification.

The second comment is more of a content issue. Ideally content follows branding and I brought up some of this in the Rivers feedback (like will there be branded content style illustrations), but I don't have a good way to solve it, especially if content will be user driven ultimately?

**Comment by lallmon** [comment]
I constrained the text and moved the button out more. The only thing that is a tough call is the button color, as the practices are colored to their loop color now, the default gray is tho only one that stands out on all backgrounds.

**Pull request merged**
