### PR TITLE
🐦  #1810 - Adds Twitter link and icon to bodyfooter

### PR DESCRIPTION
**Pull request by kattekrab**
**What issue does this PR solve?**
#1810 
🐦

### CODE REVIEW

**Comment by kattekrab** [comment]
Please review
Compare the change in this deploy preview
https://deploy-preview-1812--openpracticelibrary.netlify.app/page/contribution-guide 

against production
https://openpracticelibrary.com/page/contribution-guide

**Comment by kattekrab** [comment]
Tests are failing due to secrets config - I really do need to figure out how to manage that better.

**Comment by kattekrab** [comment]
copying the review from @eliseelk provided via chat
18 Apr, 17:30 - looks great and works well imo! well done Donna

@tim-stasse - can you please review & merge?

**Comment by kattekrab** [comment]
@tim-stasse

**Review by tim-stasse — APPROVED** [review]

**Pull request merged**
