### PR TITLE
Adding gitter chat to each practice

### LINKED ISSUE #163: Comment section for feedback
Taken from physical backlog in London.

This would be a new development feature enabling members of the community to add comments, questions and feedback on specific practice content.

### PR DESCRIPTION
**Pull request by springdo**
**What does this PR do?**
This PR is to add some basic chat features to the practice pages. Users will login with their GitHub account. Members of the org `openpracticelibrary` will be able to admin the groups etc too.

Resolves #163

### CODE REVIEW

**Comment by rdebeasi** [comment]
I've styled the button, and this code is ready to review and merge. The "share this practices" and "discuss this practices" language should be fixed in #168.

This change also prevents text from being hyphenated where it wrapped. Adjusting the footer to fit a discuss button caused some weird hyphenation, so I overrode those styles.

### Before
screenshot from 2018-07-27 17-39-16

### After
screenshot from 2018-07-27 17-47-23

**Comment by rdebeasi** [comment]
Ok, done for reals this time. :smile:

**Comment by springdo** [comment]
@rdebeasi  - thanks for working on the button for chat after I left on Friday! 
Unfortunately I think this feature is not working, unless I am doing something daft which is highly possible.... So, when I click the preview link I don't see the button on any of the practice pages.

I see in an earlier commit (c76c661) you removed the `<button type="button" class="btn btn-chat">Discuss This Practice</button>` to move it to the `share` area but I cannot see where the button comes back in in your commits. 

Also, when the master branch was brought into yours in the final commit, you've removed the custom/css rule from `[params]`. Was this intentional?

I can fix some of these things up if you'd like but I thought you wouldn't have submitted something that wasn't working, so hence I am questioning if I am missing something or maybe you're made edits in the theme and not the over ride? Let me know what you think

**Comment by springdo** [comment]
LGTM thank you @rdebeasi :) 🌮

**Pull request merged**
