### PR TITLE
remove non-printable unicode character

### PR DESCRIPTION
**Pull request by ahussey-redhat**
**What issue does this PR solve?**
removed non-printable "^L" character from line 162 of the practice
"story-kick-offs". This was failing to be parsed by pyyaml.

**Explain the problem and the proposed solution**
When parsing each of the practices using pyyaml, it would raise a `yaml.reader.ReaderError` exception because of an unprintable unicode character trailing line `162` in `story-kick-offs.md`.

The proposed solution removes this character.

### CODE REVIEW

**Comment by kattekrab** [comment]
Thanks @ahussey-redhat for your first contribution to OPL!!!!
🎉 🎈 🍰

**Comment by kattekrab** [comment]
@ahussey-redhat - did you get anywhere with this?  or should we close it?

**Comment by ahussey-redhat** [comment]
Hi Donna,

We couldn't get the build to complete.
Not sure why, and not sure how much effort is worth being put into
resolving this issue.

I've added handling into my Python app, so its not the end of the world.

Happy to keep trying, just unsure why I can't kickoff builds.

-Alex

**Comment by kattekrab** [comment]
it's outside the realms of my comprehension to help answer those excellent questions @ahussey-redhat 

Hrrmmm.

**Comment by kattekrab** [comment]
@ahussey-redhat, ok given you've got a work around in place, let's close this one for now, and revisit the priority of deeper investigate if it comes up again.

**Pull request closed without merging**
