### PR TITLE
First draft of new author header

### LINKED ISSUE #232: Fix share link layout
Share buttons overlap with borders. The text "share this practices" will be fixed in #260.

screenshot from 2018-07-27 13-17-47

### LINKED ISSUE #244: Update Author styling to match the designs
screen shot 2018-07-30 at 18 02 46

- [ ] Find out from @tdbeattie if he'd like to see `last updated by...` or a list of all authors who've contributed
- [ ] Find out from @Rileyi  if we want to keep the author at the top the page or bottom or perhaps both and we user test.
- [ ] Implement the `First written` section and raise an issue to discuss the `Last updated` idea as it may be low value / high effort to implement.
- [ ] Raise issue to discuss the `other-practices-by-this-author` buttons Vs picture in the loop.
- [ ] Get the circle with gaps in it as an SVG from @Rileyi .
- [ ] Fix existing bugs
    - Don't show "co-authors" if there is only one author
    - Show commas between co-authors

### LINKED ISSUE #252: Google Plus Share doesn't work
When I hit the Google Plus share icon at the bottom of a practice, I get this error:

> 403. That’s an error.
>
> We're sorry, but you do not have access to this page. That’s all we know.

Let's look into the problem and either disable this feature or fix it upstream.

### PR DESCRIPTION
**Pull request by rdebeasi**
**What issue does this PR solve?**
- Resolves #232 
- Resolves #244 
- Resolves #252 

**TO DO**
- [x] Style share icons in footer
- [x] Adjust text color & font size in author meta
- [x] Remove Google Plus
- [x] Update content so that date is last updated, not creation date

**In a separate issue/PR**
- [x] Figure out docs/workflow for updating last updated date. (Can we automate this in the CMS?)

**Explain the problem and the proposed solution**

### CODE REVIEW

**Comment by springdo** [comment]
@rdebeasi  - can you take a look at this please? I worked on the PR this morning. 
Getting the Last updated was pretty easy and perhaps we could use it instead of having the `authors` in our repo? It would definitely simplify the contribution model

See these Hugo docs [GitInfo](https://gohugo.io/variables/git/)

**Comment by rdebeasi** [comment]
Super cool - that's really useful. Maybe in the future we could use this to pull author data as well.

A few minor things:

- I noticed that the text mentions upvotes, but we of course don't have that feature yet. Maybe we could change this text to talk about sharing or discussing the practice?
- I noticed some weirdness with the small-screen view:
screenshot from 2018-08-06 10-01-04
- It looks like there's a minor merge conflict now.

This looks super cool and gets us really close to the design that Riley put together.

**Comment by rdebeasi** [comment]
Whoops, sorry - I apparently need more coffee and managed to push the wrong button.

**Comment by springdo** [comment]
@rdebeasi  - thanks for the feedback! Good spot on the funky mobile view. I have pushed a change to fixe this, the merge conflicts and the messaging on the community.

**Comment by rdebeasi** [comment]
Awesome - looks great! :rocket:

**Pull request merged**
