### PR TITLE
Create tweet-new-practice.yml

### PR DESCRIPTION
**Pull request by juliaaano**
Solves #1474

### CODE REVIEW

**Comment by juliaaano** [comment]
I have tested this with my own repo and twitter account. It works.

A few steps are required to get this working here for the Open Practice Library:

1. Create a dev account and Twitter app for https://twitter.com/practicelibrary. 
2. Set the Twitter App secrets in this GitHub repo.
3. GitHub workflow actions need to be in master branch to take effect, so the PR must be merged.

**Comment by kattekrab** [comment]
Amazing!  Thanks for the demo @juliaaano - very cool approach.
I'm going to merge this in, as soon as the tests are green again.  But I know it won't actually work, or do anything until we get the twitter secrets in place.  I will need to get the details from @heyjerrybecker for that, or we will need to work with him to get that set up.

**Comment by kattekrab** [comment]
Merged.  I might need a reminder on where and how to set the twitter creds once we have them.

**Comment by kattekrab** [comment]
Thanks @heyjerrybecker for sharing the twitter deets. 
@juliaaano I've gone ahead and applied for a twitter dev team account.

Next step is to create the app.

**Pull request merged**
