### PR TITLE
Update design-sprint.md

### PR DESCRIPTION
**Pull request by SandraArps**
Updated participants and some of the activities

**What issue does this PR solve?**

**Explain the problem and the proposed solution**

### CODE REVIEW

**Comment by rdebeasi** [comment]
Thank you for the contribution! Looks like there's a merge conflict here. We'll work with you to get that resolved.

On the content front, the suggestion to include a "Sales Manager / Customer Representative" isn't covered in the _Sprint_ book. I think it might be worth discussing this idea further before we make the change.

I see a design sprint as a discovery/delivery activity, not a sales activity. Colleagues who have treated a design sprint as a sales activity have reported that clients sometimes treat the resulting prototype as a "statement of work" and dive into waterfall-style delivery. Treating a design sprint as part of discovery and delivery, not sales, may help alleviate this problem.

I'm definitely open to other perspectives on this, and I'd love to hear your thoughts. @tdbeattie @beckerjs @mtakane @DarcieF , what do you think?

**Comment by SandraArps** [comment]
Sorry, I should have been more specific. It is not the Red Hat Sales team. It is the customer sales team.
A person from the sales team is required to provide input to the product idea. The sales team / customer representative is the person who works closely with the user. They are the first to find out about complains. Having them participate in the DS can greatly approve the outcome.
At Heritage Bank we had the 'Banking Branch' Manager in the sprint. She was excellent in providing insights into HB end users.
Hope this make sense.

**Comment by rdebeasi** [comment]
Gotcha - thanks for clarifying! In that case, I'm 110% onboard with that change. :smile: :rocket:

**Comment by rdebeasi** [comment]
Resolved conflict - merging!!

**Comment by SandraArps** [comment]
THANK YOU ;-)

Warm regards,

Sandra Arps
Open Innovation Lab - Engagement Lead - APAC
E: sarps@redhat.com
M: +65 8283 0780

**Pull request merged**
