### PR TITLE
Add optimistic merging guide

### LINKED ISSUE #208: Optimistic Merging Guidelines
# Optimistic Merging Guidelines

We've discussed "optimistic merging" for pull requests on this project, but there are some questions on what exactly that term means.

To address that disconnect, I'd like to propose some specific guidelines. If there's consensus on these ideas, I'll write up a document explaining our decision and submit it as a PR.

## Background

Optimistic merging was first proposed a few years ago by Pieter Hintjens of the ZeroMQ community in a blog post called [Why Optimistic Merging Works Better](http://hintjens.com/blog:106). That project's [Collective Code Construction Contract (C4)](https://rfc.zeromq.org/spec:42/C4/) is an expanded and formalized version of the same idea.

Here's the workflow as I understand it:
1. To propose a change, log an issue.
2. Seek consensus on the value of that change.
3. Create a pull request to make the change described in the issue.
4. The maintainer checks to see whether the change is a "correct patch".
5. If the PR is a "correct patch", the maintainer merges the PR.

A "correct patch" is one which:
- Solves one "identified and agreed problem"
- Doesn't break APIs (see ["Evolution of Public Contracts"](https://rfc.zeromq.org/spec:22/C4/#evolution-of-public-contracts))
- Compiles cleanly and passes tests
- Clearly explains the problem and the proposed solution

## Examples

For some examples of how optimistic merging happens in the real world, see [ZeroMQ's closed pull requests](https://github.com/zeromq/libzmq/pulls?q=is%3Apr+is%3Aclosed).

Contributors make small PRs that each solve one agreed-upon problem. The PRs include detailed commit messages documenting the problem and solution, usually with a reference back to the associated issue.

In exchange, maintainers merge correct patches quickly and give clear, concise feedback on incorrect patches. The patch might be deemed incorrect if [tests fail](https://github.com/zeromq/libzmq/pull/3137) or the PR [doesn't follow C4](https://github.com/zeromq/libzmq/pull/3032). In that case, contributor either makes the requested changes or closes the PR.

Both contributors and maintainers do some extra work to make this rapid feedback loop happen, and everyone checks their egos at the door. Landing a patch isn't a fight; it's more like a careful dance.

## What does this mean for the Library?

There are of course a few differences between ZeroMQ and the Open Practice Library. ZeroMQ is a large, mature piece of software. The Open Practice Library is young (but growing!) project that's a mix of content and code. ZeroMQ has a formal release process; the last stable release was [4 months ago](https://github.com/zeromq/libzmq/releases/tag/v4.2.5). The Open Practice Library has no formal release process; the site is automatically deployed as soon as a PR is merged. The last release of the Library was - _checks watch_ - [20 minutes ago](https://app.netlify.com/sites/openpracticelibrary/deploys?filter=master).

I like the speed with which we're shipping changes and don't want to slow down, but the trade-off is that we have to take some care. If a ZeroMQ maintainer merges a bug, the community has time to fix the bug before release. If we merge a bug, it's immediately shipped to production.

You can't write automated tests for practices, of course. Instead, I propose that we use the [Contributing Guide](https://github.com/openpracticelibrary/openpracticelibrary/blob/master/CONTRIBUTING.md) as a sort of "unit test for content." If the "tests" in this guide fail, the PR must be modified so that they pass before it can be merged. If the tests pass, the PR can be merged immediately.

We can (and should!) write tests for our code, but work on our current iteration began last week, and as a result we currently have a test coverage of 0%. Right now, the project is changing so rapidly that we'll probably invalidate tests almost as quickly as we write them. I propose that we use a combination of automated and manual testing for code PRs.

We recently added automated deploy previews as a first step towards a full CI/CD pipeline. As our codebase stabilizes and our test coverage increases, we'll aim to gradually reduce the amount of manual testing to zero.

## tl;dr

With the considerations above, I think the Optimistic Merging/C4 guidelines apply pretty nicely to our project. Well-formed patches are accepted quickly. If a patch fails CI or doesn't solve an agreed-upon problem, the maintainer provides kind, constructive, clear feedback, and the community moves forward.

A review is a rapid feedback loop, not meaningless bureaucracy or a rubber stamp. To misquote Mark Zuckerberg, move fast and _don't_ break things.

I'd very much like to hear the community's opinions on this topic. Please feel free to leave comments on this issue.

Thank you for your time, and be excellent to each other.

### PR DESCRIPTION
**Pull request by rdebeasi**
**What issue does this PR solve?**
Resolves #208

**Explain the problem and the proposed solution**
Add the process that we discussed, along with some context, to the developing guide.

Before this is merged, we should:
- Double-check with the community
- Decide whether we want this content to apply to all changes, or just to dev changes

### CODE REVIEW

**Comment by mtakane** [comment]
I like using it for both code and content. 

One question on it. Can netlify link its bot PRs to an existing issue? I don't think it can, so should we look to figure out (in a future issue/PR) how we can identify a netlify-bot PR to the issue it is looking to solve? OR look for a different path.

**Comment by rdebeasi** [comment]
Agreed - the Netlify-bot setup can't do that, so let's look to solve that in a future PR.

**Comment by rdebeasi** [comment]
I've let this sit a couple of days for feedback, so I'm removing "WIP" from the title. @springdo , feel free to review whenver you're ready.

**Comment by springdo** [comment]
LGTM -  🌮 🌮 🌮 🍺

**Pull request merged**
