### PR TITLE
Add perspective content type

### PR DESCRIPTION
**Pull request by rdebeasi**
**What issue does this PR solve?**
There isn't a good place for content such as "Domain-Driven Design" and "Product Ownership". These pages describe ideas or mindsets, not practices that you could actually run.

**Explain the problem and the proposed solution**
- Add a new "perspectives" content type as discussed in #376.
- Implement a field where these perspectives can be linked to practices.
- Implement a first draft of the UI sketch in #376. Practices display the related perspectives, and vice-versa.
- Turn DDD and product ownership into perspectives, and link them to corresponding practices.
- Merge practice layout into default layout so that we can reuse it for perspectives.
- Update Netlify instructions to cover quirks that I encountered while developing.

**What's not in this PR**
- A full implementation of the UX shown in #376. I plan to submit a second PR with those changes. 
  - In particular, the practice listing page is pretty bare-bones right now.
- An elegant interface for selecting practices - see #501.
- Reorganization of foundation practices that may belong elsewhere - see #375.
- A final decision on the term "perspectives" - we may need to wrap up the discussion in #376 before this can be merged.

@springdo , does the code look ok to you?
@sherl0cks @tdbeattie @mtakane , does the organization of the content look ok to you?

### CODE REVIEW

**Comment by tdbeattie** [comment]
Nice feature @rdebeasi - thank you for adding it.

The organisation of content does indeed look good based on our previous discussions.

**Comment by sherl0cks** [comment]
@rdebeasi should I expect to still see the perspectives listed as practices? I see that with both perspectives

**Comment by rdebeasi** [comment]
Hm, you should not see perspectives listed as practices. Where are you seeing that? I'm not seeing "product ownership" or "domain-driven design" on https://deploy-preview-505--openpracticelibrary.netlify.com/.

**Comment by sherl0cks** [comment]
Ahhhh that's me getting lost in the navigation of preview, which is sending me to production. Looking just at the preview, this looks good to me. It will break existing links though, anything we should do about that?

**Comment by rdebeasi** [comment]
Yeah, that's a good point. The content is new enough that it _probably_ doesn't have any incoming links, but it would be good to get into the habit of adding redirects when we move stuff. I'll set up some redirects and then update the PR accordingly.

**Comment by sherl0cks** [comment]
:+1:

**Comment by mtakane** [comment]
this looks good to me. opening a few more issues for some items missing to help with context in the site. (#520 for instance is something we will need)

**Pull request merged**
