### PR TITLE
added instructions for how to use docker during development

### PR DESCRIPTION
**Pull request by tenfourty**
Short instructions for how to use a well maintained docker image for hugo instead of locally installing node, hugo and npm install etc.

### CODE REVIEW

**Comment by rdebeasi** [comment]
Cool - I totally agree that the setup instructions are way too complicated currently.

This image doesn't include node/npm as far as I can tell, which is needed in order to work on the parts of the site that handle search. In the near future, the plan is to wrap the site setup in an npm build and remove the "install hugo"/"run hugo" steps - see #154 for details. At that point, a working Node installation (or a Node.js Docker image) would probably be the right tool for the job.

Where content writers no longer need a local setup and developers won't get complete functionality from this Docker image, I'd propose closing this issue for now and revisiting the instructions once #154 is done.

**Comment by rdebeasi** [comment]
For what it's worth, deploy previews handle the "get a quick preview of your work." I also have some concerns about the trustworthiness of an unofficial Hugo image. 

Could we change these instructions to say something like, "Install Hugo, init the submodules, and run hugo serve"? That handles this use case without relying on an unofficial image or requiring that the user install Docker.

**Comment by tenfourty** [comment]
Personally, I do all my deploy previews with my local machine, that is what this use case is for.

The reason I'm offering instructions for my personal workflow is that it might be useful for others who also don't want to install a bunch of tools on their local machine but would rather use a pre-built docker image that takes a few seconds to run.

I'm not trying to contribute instructions for the "normal" workflow but just a simple MVP for those that would prefer to use Docker instead, it works well for me and I thought others would get value from it, so I would rather not change this PR to incorporate your suggestions as it doesn't make sense.

Either you would like to accept a PR that has some instructions to Docker and you accept it (and fix it if you think things can be done better) or just reject it if you don't think this approach is valid.

I don't think the docker hub security issue is relevant here, the reason why is that this is not the image we use for final product to be hosted but rather just to quickly get hugo running (for those with docker) and nothing more - the way the image works I don't think there are a lot of security concerns and it's a well maintained and fully open source community image.

**Comment by rdebeasi** [comment]
> I'm not trying to contribute instructions for the "normal" workflow but just a simple MVP for those that would prefer to use Docker instead, it works well for me and I thought others would get value from it, so I would rather not change this PR to incorporate your suggestions as it doesn't make sense.

Totally fair. To me, the README is there to describe the "normal" workflow. Let's improve that workflow rather than adding a second one. Asking new contributors to pick from two separate workflows isn't a good onboarding experience.

**Pull request closed without merging**
