### PR TITLE
Update the Feature Toggles article

### PR DESCRIPTION
**Pull request by tenfourty**
**What issue does this PR solve?**

This PR updates the article on Feature Toggles/Flags.

**Explain the problem and the proposed solution**

Problem: Update of the article on the foundational engineering practice of Feature Flags (or Toggles) - this problem is described here https://github.com/openpracticelibrary/openpracticelibrary/issues/868#issuecomment-570805680
Proposed Solution: this pull request updates @valyonchev original article on Feature Toggles to solve the issues described in the issue above.

### CODE REVIEW

**Comment by tenfourty** [comment]
Edits done, this is ready for review.

**Comment by tdbeattie** [comment]
LGTM

**Comment by valyonchev** [comment]
Oh, wow. That is a lot better in terms of content and details. I have a few important questions, though. Let me know what you think about those so we can move forward.

1. Why is this practice not a good fit for the Options Pivot?
2. If it takes at least a developer and a product owner to discuss and decide on what gets a toggle, should the number of people be 1+? How do we emphasize the collaborative side of this practice?
3. How would describe the purpose of this practice from a product development perspective?

I am concerned that the language and point of view is very focused on engineering and lacks the perspective of the complete product team or at least the product manager/owner. If one considers this practice as purely engineering practice, that makes sense. However, my PoV is that this practice is a lot more than engineering only.

I've already made some comments on my point of view in the issue thread https://github.com/openpracticelibrary/openpracticelibrary/issues/868

**Comment by tenfourty** [comment]
Hi @valyonchev good points, let me answer them one by one:

- options pivot vs foundational technical practice - IMHO feature toggles are an engineering practice that is foundational to a culture of experimentation. Implementing a feature toggle requires some level of engineering effort and code changes. It is not something that (typical) product managers or designers would implement but rather does require an engineer/developer.

- number of people - a single person product team could implement this practice, in fact many one person companies use this practice, just because the minimum required people is one doesn’t detract from the potential collaborative nature of this practice. In addition as this practice could be used for purely technical purposes (trunk based development) I think the minimum of one still makes sense.

- the purpose of this practice from a product development perspective? Honestly it varies based on how you want to use feature toggles. That said from my experience this is a fundamental engineering practice to be able to ship faster and reduce lead times (trunk based development) and as you evolve further you can start to use it for uses like dark launches, canary deployments and A/B testing etc. But I’ve found there is an evolution in terms of maturity to being able to use this practice and the level of things you use it for. At it’s most basic level it is still an engineering practice that needs a certain level of maturity to use.

I **do** agree that this practice is much more than just engineering, but it does require engineers to implement this practice. Feel free to continue to refine this article to improve the language via another PR.

**Comment by tdbeattie** [comment]
Hey @valyonchev - any thoughts / feedback on @tenfourty's latest updates on this PR?

I'd be ok to OM this in but would be even better if we could reach consensus between original author and the author of the patch.

To add a couple of thoughts:

- There are several practices that can be positioned in different areas of the library. I generally suggest that the best location is where it might **first** be used. So, applying that approach, do we assume that we create Feature Toggle capability in the technical foundation before the business see a need for it or do we wait for it to it to become a business discussion when assessing Options and then do the technical foundation work as a part of the delivery of the feature we want to include a toggle on?

- Most other of the advanced deployment type practices actually sit on the loop - some in Options Pivot and some in Delivery. ([Split Testing](https://openpracticelibrary.com/practice/split-testing-multivari-testing/), [Canary Release](https://openpracticelibrary.com/practice/canary-release/), [Blue/Green Deployments](https://openpracticelibrary.com/practice/blue-green-deployments/) and [Dark Launches](https://openpracticelibrary.com/practice/dark-launches/) are a few examples. All of these require engineering capability to enable the advanced deployment capability. Perhaps we need a separate technical foundation practice to enable Advanced Deployments.

- I looked at the Mobius Community cards and they actually use Feature Toggles on the Delivery Loop.

**Comment by tenfourty** [comment]
Hi @valyonchev and @tdbeattie as to where the practice should sit, if the test is where in the loop this will be used first, then I would strongly suggest it is an engineering practice in the foundation. To provide some data on this, here is what [Optimizely say about why they are offering their rollouts product for free](https://www.optimizely.com/rollouts/):

> Building a culture of experimentation in product development is hard. Our ambition is to make it easy. It can be an uphill battle to change an organization’s culture, especially if it costs a lot of money upfront. That's why we're launching Optimizely Rollouts for free. Because we believe rolling out features is just a step on the journey to experiment-driven product development, we want to help every company work this way. As companies mature, the next step on the journey is embracing A/B testing as part of the process of rolling out features.

It would be great to get this PR merged at some point...

**Comment by tdbeattie** [comment]
I'm good to merge this and we can open separate GitHub issues to discuss and address further improvements to the practice. 

Thanks!

**Comment by valyonchev** [comment]
Sorry, flooded with stuff and some sick leave in between.
Thanks for merging it.

**Pull request merged**
