### PR TITLE
Update docs-as-code.md

### PR DESCRIPTION
**Pull request by alecthegeek**
Add more concrete suggestions.

It helps the reader get started with Docs As Code by providing suggestions on specific tools for some of the more advanced practices.

### CODE REVIEW

**Comment by kattekrab** [comment]
Tests failing. Will investigate.

**Comment by kattekrab** [comment]
Hey @alecthegeek - firstly, apologies for taking so long to review - it's been a busy few weeks.
I suspect the tests might be failing because you submitted this PR via github, rather than editing via the CMS - could that be the case?

The deploy preview looks good though, so I'm going to merge it anyway, and just cross my fingers
https://deploy-preview-2206--openpracticelibrary.netlify.app/practice/docs-as-code/

**Comment by alecthegeek** [comment]
Looks good to me

**Comment by kattekrab** [comment]
And updates now live in prod! Thanks @alecthegeek 
https://openpracticelibrary.com/practice/docs-as-code/

**Comment by alecthegeek** [comment]
Oops -- saw a format error. Managed to fix it via the CMS interface. Ready for review

**Pull request merged**
