### PR TITLE
Remove labs specific content

### PR DESCRIPTION
**Pull request by tdbeattie**
I've reviewed all existing content and made updates where there was specific reference to "Labs" and "residencies".

For now, I've kept the links to few resources on Red Hat G Drive but will raise separate issue to look at these another time.

### CODE REVIEW

**Comment by tdbeattie** [comment]
@springdo  - please can you take a look at the conflict?

**Comment by mtakane** [comment]
I removed the RH specific resource section as we need to be more friendly and not "you get some but not all resources". The other changes looked good. I would like to get 1 last review on the removal of that section before final merge pls.

@rdebeasi mind if you take a look on the last commit? Simple removal of a section on key practice pages.

**Comment by rdebeasi** [comment]
Looks good to me! In the future, let's make those internal-only resources publicly available! I've added #182 for that change.

**Comment by tdbeattie** [comment]
Cool. Thanks both for reviews and additional commit. I'll go ahead and merge.

**Pull request merged**
