### PR TITLE
Add "What's new" to navigation

### LINKED ISSUE #258: Status blog
Let's share status updates on the practice library itself. Currently we're doing this via a mailing list, but there have been requests to publish this information so that it's a.) shareable and b.) available to the public.

Ideas:
- Hugo blog posts in openpracticelibrary.com
- Public-facing email list (maybe generated from blog posts?)

### PR DESCRIPTION
**Pull request by rdebeasi**
**What issue does this PR solve?**
There isn't currently an easy way for viewers of openpracticelibrary.com to see what's changed recently. Resolves #258.

**Explain the problem and the proposed solution**
This PR adds a "what's new" link to the nav and the homepage. This link goes to the [list of PRs that have been merged to master](https://github.com/openpracticelibrary/openpracticelibrary/pulls?q=is%3Apr+is%3Aclosed+base%3Amaster). It's not as nice as a status blog or a Twitter feed, but it does the job and requires very little maintenance. We'll just need to be sure to write descriptive PR titles when merging to master.

This PR also moves "contribution guide" up a few spots so that all the "internal" links appear together.

**Other solutions we investigated**
- Consuming an RSS feed in a static site like ours would probably involve client-side RSS parsing. That's bad for performance and SEO reasons.
- In the future, GitHub's Releases feature might be a better solution, but because of [technical limitations](https://github.com/openpracticelibrary/openpracticelibrary/issues/258#issuecomment-441709981), it isn't a good solution for us today.
- We don't have the capacity to manually write content for an update blog or Twitter feed - see the discussion in #258.

### CODE REVIEW

**Comment by rdebeasi** [comment]
Ping @tdbeattie @mtakane

**Comment by rdebeasi** [comment]
FYI, I'm going to self-merge this change if I don't hear back in the next 24 hours. I appreciate that folks are swamped and might not have time to look at this. Thanks!

**Comment by springdo** [comment]
As a suggestion - could we write some kinda release notes of the new items being added when moving the library from staging to prod. Then have those as the what's new?

**Comment by rdebeasi** [comment]
Sure! We've done something similar with recent merges to master - see #552 and #522.

Would you want to see documentation or something else to formalize this a bit more?

**Comment by rdebeasi** [comment]
I forgot to mention that longer-term, I'd like to use GitHub releases for this. We're not ready for that for reasons discussed in https://github.com/openpracticelibrary/openpracticelibrary/issues/258#issuecomment-441709981.

**Comment by rdebeasi** [comment]
It sounds like a better release process can be defined in a future PR/issue. I haven't heard back in about a week, so I'm going to go ahead and self-merge this. Thanks again for the feedback!

**Pull request merged**
