### PR TITLE
The CoC Link was pointing to staging branch

### PR DESCRIPTION
**Pull request by erikbgithub**
**What issue does this PR solve?**

The link to the CoC didn't work as it was pointing to the wrong branch. I changed it to the right branch.

**Explain the problem and the proposed solution**

I'm not really sure what I can write here that I didn't say for the first question already.

### CODE REVIEW

**Comment by erikbgithub** [comment]
@springdo Looks like the E2E test itself has a problem?
The preview deploy contains the right link now and it works via manual test.

**Comment by erikbgithub** [comment]
@kattekrab This is the first PR as discussed on [LinkedIn](https://www.linkedin.com/feed/update/urn:li:activity:6823654757366861825?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6823654757366861825%2C6824255663057719296%29).

**Comment by kattekrab** [comment]
Hey @erik Thanks so much for the bug report AND the fix!
Whoohooo.

Thanks again for your patience while I sort out the issues preventing merge.
If I can't get that done quickly, I'll do this fix manually!

**Comment by kattekrab** [comment]
I'm going to throw caution to the win, merge and see what happens.  But updating the branch first just in case.

**Pull request merged**
