### PR TITLE
Set GHA virtual environment to use Ubuntu LTS (ubuntu-20.04)

### LINKED ISSUE #1568: Test Warnings - Need to upgrade Ubuntu
WE have a test warning saying our OS is deprecated.  It would be great to get that fixed.

```
E2E Tests : .github#L1
The ubuntu-16.04 environment is deprecated and will be removed on September 20, 2021. 
Migrate to ubuntu-latest instead. 
For more details see https://github.com/actions/virtual-environments/issues/3287
```

### PR DESCRIPTION
**Pull request by tylerauerbeck**
**What issue does this PR solve?**

Fixes #1568 

This sets all of our Github Actions to run against the LTS version of Ubuntu which will resolve the existing issue and also protect us from potential changes that are made to latest (which have caused us small issues in the past).

**Explain the problem and the proposed solution**

Update the workflow files and 🚀  no more warnings 🚀

### CODE REVIEW

**Comment by springdo** [comment]
@tylerauerbeck - looks like your base of the master is out of date, any chance you can bump it please? 🦆

**Comment by tylerauerbeck** [comment]
@springdo 🚀  Done

**Comment by kattekrab** [comment]
Yay! Thanks @tylerauerbeck and @springdo for looking at this!
It looks as though we may need some env var jiggery pokery to do before this can be merged.

**Comment by kattekrab** [comment]
@springdo @tylerauerbeck - tests still aren't green for this - so I'm reluctant to merge as I don't know if it will break anything.  Can one or both of you take a look and let me know?

**Comment by tylerauerbeck** [comment]
@kattekrab Yepp. Something doesn't seem quite right here. Will try to take a look tomorrow.

**Comment by kattekrab** [comment]
Thanks Tyler!

Via mobile.

**Comment by kattekrab** [comment]
@itblaked see if you can take look here too. Maybe?

**Comment by itblaked** [comment]
Hey, 

- I realised this PR addresses two issues so I've linked the 2nd issue to the PR as well.
- The code changes of the PR aren't actually tested by the pipeline as the code changes are to the pipeline itself. 
  - To confirm that the new pipeline executes successfully for a standard content branch, I merged this PR into a new branch at `openpracticelibrary:update-virt-env` so that we can test the new pipeline and left the issue open until the changes are tested and we successfully merge into master.
  - I also created a new branch `test-new-pipeline/wheel-of-misfortune` which is based on a PR for a new practice which has passed all tests for the existing pipeline and is pending merge. I see this as a good candidate to test the new pipeline with.
  - I raised PR #1604 to merge this test branch into the new pipeline branch and it passed all tests successfully in the new pipeline and validates that:
    - The base OS is updated to Ubuntu 20.04 as required by #1568 .
  - I also raised PR #1606 which has successfully validated that:
    - The changes to address #1571 do not impact normal content merge.

**Comment by itblaked** [comment]
@tylerauerbeck given the above has now successfully tested the changes, can you please raise PR again against master?

@kattekrab previous comment and effort details how the changes were validated, let me know if you want to step through them before approving the new PR from @tylerauerbeck when it arrives.

**Comment by itblaked** [comment]
@tylerauerbeck disregard previous comment about raising PR, realised I can do this for you :)

**Pull request merged**
