### PR TITLE
[#1474] Add a simple bot that can tweet a random practice.

### PR DESCRIPTION
**Pull request by cafuego**
**What issue does this PR solve?**

Solves issue #1474

**Explain the problem and the proposed solution**

The project owner wants to automatically post practices to twitter. This is a small nodejs based bot that can post a random practice to twitter, once authenticated. The tweets are more or less templated, so can be changed relatively easily.

### CODE REVIEW

**Comment by kattekrab** [comment]
This is amazing! The netlify Deploy summary looks good.
I've approved the workflow so the tests can run.  Now, let me see if we can get someone to review properly!
Thank you @cafuego !!

**Comment by kattekrab** [comment]
Learning by learning.

Thanks to @itblaked for pairing with me yesterday to uncover info on how our pull requests work, or don't work, in this case.
That's by design at this stage, so will need to dig a bit further into how to streamline merging contributions from people outside the org.

Next step for this one is for me to have a go at running it locally.
Thanks @cafuego

**Comment by juliaaano** [comment]
@kattekrab please consider PR #1566 and close this one in case that one is approved.

**Comment by kattekrab** [comment]
Righteooo - looks like @juliaano's github actions approach has done the trick!  Thank you @cafuego for having a crack - it paved the way.

**Pull request closed without merging**
