### PR TITLE
event storming spanish initial

### PR DESCRIPTION
**Pull request by sdstolworthy**
**What issue does this PR solve?**
Initial Spanish translation for Event Storming

**Explain the problem and the proposed solution**

### CODE REVIEW

**Comment by sdstolworthy** [comment]
I am putting this up here just so the content is available in md. I didn't convert the tags over yet because I thought it required me to make some assumptions about how you all plan to implement i18n.

**Comment by shaheinm** [comment]
> I am putting this up here just so the content is available in md. I didn't convert the tags over yet because I thought it required me to make some assumptions about how you all plan to implement i18n.

Thanks! You should copy the frontmatter format you see in the english file. We're not implementing i18n at all right now, and the content itself would be separate from anything we did in code anyway. In any case, I'd suggest leaving the tags as-is for now, particularly the mobiusTags key.

**Comment by shaheinm** [comment]
Converted this to draft just to avoid confusion about open PRs on OPL

**Comment by kattekrab** [comment]
Given we don't have immediate plans to do I18N properly - perhaps we should just publish this "As Is" as a seperate practice, and make sure we link between the spanish and english versions.

Could that work?

**Comment by kattekrab** [comment]
@sdstolworthy and @MaggiePerera are working on the practice content.  When they're done, we'll publish this as a new practice for now - until we can figure out how we want to do multi-lingual properly.

**Comment by kattekrab** [comment]
@sdstolworthy and @MaggiePerera can I suggest we add your new spanish and portugues translations via netlify, and just close out this PR?  I've also asked Jenny and Song to consider adding Chinese and Korean translations.

**Comment by kattekrab** [comment]
Yay! closing this, and reviewing #1645 instead!

**Pull request closed without merging**
